name: "Docker action demo"
description: "A demo action"
inputs:
  who-to-greet:
    description: "Who to greet"
    type: string
    required: true
    default: "World"
outputs:
  time:
    description: "The time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}