name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet: # Define the input parameter
        type: string
        description: 'Who to greet'
        required: true
        default: 'World'
    outputs:
      current-time:
        description: 'The time the job finished'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.date.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      
      - name: Get the current time
        id: date
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
        
