name: Reuse a workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: 'Madkoo'

  use-outputs:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Get the output
        run: echo "The current time is ${{ needs.call-reusable-workflow.outputs.current-time }}"

      
